version: '3'
services: 
  redis:
    image: "redis:alpine"
    ports: 
      - 6379:6379

  nginx:
    image: "nginx:alpine"
    extra_hosts: 
      - dockerhost:${HOST_IP}
    ports:
      - 8050:80
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro