version: '3'

services:  
  redis:
    image: "redis:alpine"
    ports: 
      - 6379:6379

  loadbalancer:
    image: "nginx:alpine"
    extra_hosts: 
      - dockerhost:${HOST_IP}
    ports:
      - 8050:80
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  app:
    build:
      context: .
    expose: 
      - 8080
    depends_on: 
      - redis
    links: 
      - redis
    networks: 
      default: 
        aliases: 
          - web-apps